[package]
name = "error_server"
version = "2.0.0"
edition = "2021"
repository = "https://github.com/SIMULATAN/ErrorServer"

[dependencies]
signal-hook = "0.3.14"

[profile.release]
opt-level = 3
panic = "abort"
lto = true
strip = "symbols"
